\backmatter

# Backmatter 



## Colophon 

This document is typeset with LaTeX using a custom template based on KOMA-script SCRBOOK class. The layout is based on a standard A4 paper (210 x 297mm), with 40mm margins and 10mm of binding offset.

The typesetting software used the XeTeX engine and the text is set in the open source IBM Plex font family -- in Serif, Sans Serif and Monospace variants.


## Credits 



This project is constituted by files written in Markdown syntax and exported either as a standalone website both as printer-ready product. This is due to the awesome work of the people behind different libraries:

* [Pandoc](https://bookdown.org)
* [Bookdown](https://bookdown.org) 
* [RMarkdown](https://bookdown.org) and [R](https://bookdown.org) environment.

As well, for the computational infrastructure, a lot of open source tools have been used:

* [NLTK](https://bookdown.org)





## About the author 

I am a Graduate Researcher involved in a Ph.D. Program in Italian Linguistics at the Department of Romance Studies in the Faculty of Philosophy at Palacky University in Olomouc, Czech Republic.

My interests span across digital humanities, syntax theories and computational linguistics.

Feel free to write me at [marco.petolicchio@gmail.com](mailto:marco.petolicchio@gmail.com) or visit [marcopetolicchio.com](http://marcopetolicchio.com) for the detailed contact list.




## Progress in the repository 

This graph represents the addition and deletion amount in the files of the project in function of time.

```{r fig.width=7, fig.height=4, echo=FALSE, message=FALSE}

library(ggplot2)
library(knitr)

options(kableExtra.latex.load_packages = FALSE)
library(kableExtra)



dat <- read.csv("gitstats.csv", header=FALSE)
dat[is.na(dat)] <- 0
mat <- as.matrix(dat)

times <- mat[,3]
fileChanged <- mat[,5]
adds <- mat[,6]
dels <- mat[,7]

times <- as.Date(times)

prova <- ggplot(dat, aes(x=times, y=cumsum(adds))) + geom_line()


dels <- as.integer(dels) * -1
diffs <- as.integer(adds) + as.integer(dels)
prova2 <- ggplot(dat, aes(x=times, y=diffs)) + geom_line()




out <- ggplot() + geom_point(data=dat, aes(x=times, y=cumsum(adds), color = "Additions")) + geom_point(data=dat, aes(x=times, y=cumsum(dels), color = "Deletions"))  + geom_line(data=dat, aes(x=times, y=cumsum(diffs), color = "Difference")) + geom_point(data=dat, aes(x=times, y=cumsum(fileChanged), color = "Files Changed")) 

#+ xlab('Dates') + ylab('Edits')

print(out)

#kable(dat[,3:7])

```