--- 
title: "Italian as Second Language in native Czechs and Slovaks"
subtitle: "From the development of a learner corpus towards a theoretical investigation"
author: "Marco Petolicchio"
date: "`r Sys.Date()`"
site: bookdown::bookdown_site
output: bookdown::gitbook
documentclass: scrbook
lot: yes
lof: yes
classoption: [a4paper,twoside,12pt,chapterprefix=false, bibliography=totocnumbered,listof=flat]
bibliography: [bibliography.bib]
biblio-style: apa
link-citations: yes
github-repo: p-marco.github.io/phd-thesis
description: "My PhD thesis"
always_allow_html: yes
---

# Preface {-}
## Abstract {-}


The main topic of this doctoral dissertation is on the analysis of syntactic structures in language acquisition,  specifically in the domain of Czech and Slovak learners which acquire the Italian language. In particular, I will focus on the complex noun phrase subdomain, showing the compositionality of the phrase structure and the hierarchical fashion of this component. 
The analysis is casted in the Minimalist-oriented framework of the Generative Grammar [@chomsky1995; @chomsky1998; @chomsky2013; @hcf2002] and its application in the field of the second language acquisition [@rothmanslabakova2017;  @slabakovalealliskin2014].

The usage of an established computational ground to conduct the work, where the data retrieved by fieldwork is stored in a coherent corpus which easily permits to be queried and interpolated for the research purposes, represents a standpoint for this research in its totality, yielding for a data-based approach to the whole process. 
The annotation schema of the data is standardized in order to adhere to the major point of discussion into the discipline [@clark2010; @kueblerzinsmeinster2015; @kurdi2016], representing the plus to furnish a data source which is independent to the merely contingent purposes.

This research aims to offer a way to investigate how second language acquisition can be seen grounding on a coherent set of data in terms of annotation schema: it does insist either on the speculative questions both on computational models involved.





## Keywords {-}
Computational Linguistics; Syntax; Second Language Acquisition; Italian L2; Corpus Linguistics.


## Progress in the repository {-}

```{r fig.width=7, fig.height=4, echo=FALSE, message=FALSE}

library(ggplot2)
library(knitr)

options(kableExtra.latex.load_packages = FALSE)
library(kableExtra)



dat <- read.csv("gitstats.csv", header=FALSE)
dat[is.na(dat)] <- 0
mat <- as.matrix(dat)

times <- mat[,3]
fileChanged <- mat[,5]
adds <- mat[,6]
dels <- mat[,7]

times <- as.Date(times)

prova <- ggplot(dat, aes(x=times, y=cumsum(adds))) + geom_line()


dels <- as.integer(dels) * -1
diffs <- as.integer(adds) + as.integer(dels)
prova2 <- ggplot(dat, aes(x=times, y=diffs)) + geom_line()




out <- ggplot() + geom_point(data=dat, aes(x=times, y=cumsum(adds), color = "Additions")) + geom_point(data=dat, aes(x=times, y=cumsum(dels), color = "Deletions"))  + geom_line(data=dat, aes(x=times, y=cumsum(diffs), color = "Difference")) + geom_point(data=dat, aes(x=times, y=cumsum(fileChanged), color = "Files Changed")) 

#+ xlab('Dates') + ylab('Edits')

print(out)

#kable(dat[,3:7])

```